server:
  port: 8600
  address: localhost
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: dmoim-api-gateway
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8700
  cloud:
    gateway:
      #      default-filters:
      #        - name: GlobalFilter
      httpclient:
        connect-timeout: 6000
        response-timeout: 3000
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
      routes:
          - id: dmoim-api-user
            uri: http://localhost:9000/
            predicates:
            - Path=/api/users/**, /api-docs/users
            order: 0
#        - id: dmoim-api-board
#          uri: http://localhost:9010/
#          predicates:
#            - Path=/api/boards/**

logging:
  config: classpath:log/log4j2.yml

springdoc:
  swagger-ui:
    operations-sorter: method
    display-query-params: true
    display-request-duration: true
    deep-linking: true
    show-common-extensions: true
    show-extensions: true
    persist-authorization: true
    use-root-path: true
    filter: true
    try-it-out-enabled: true
    csrf:
      enabled: true
    urls:
      - url: http://localhost:9000/api-docs/users
        name: 사용자 API

