server:
  port: 9000

spring:
  messages:
    basename:
  r2dbc:
    name: h2
    username: user
  webflux:
    format:
      date: iso

logging:
  file:
    path: classpath:log/


springfox:
  documentation:
    swagger-ui:
      base-url: