server:
  port: 9000
  address: localhost

spring:
  application:
    name: dmoim-user-service
  messages:
    basename: i18n/message
  r2dbc:
    name: h2
    username: user
  webflux:
    base-path: /api
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: iso
      time: HH:mm:ss

logging:
  config: classpath:log/log4j2.yml

springdoc:
  swagger-ui:
    path: /api-docs.html
