server:
  port: 9000
  address: localhost
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: dmoim-user-service
  messages:
    basename: i18n/message
  webflux:
    base-path: /api
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: iso
      time: HH:mm:ss

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    use-root-path: true
    operations-sorter: method
    filter: true
    try-it-out-enabled: true

logging:
  config: classpath:log/log4j2.yml
